const CATALOG = [
    {
        id: 1,
        name: 'Ноутбук Apple Macbook Air 13" M1 2020 MYD92',
        imgLeft: '/img/catalog/macbook.jpg',
        imgCenter: '/img/catalog/macbook-2.jpg',
        imgRight: '/img/catalog/macbook-3.jpg',
        price: 5080,
        ttlprice: 5080,
        oldPrice: 5200,
        available: 10,
        term: 879801,
        filter: 'macbook',
    },
    {
        id: 2,
        name: 'Ноутбук Apple Macbook Pro 13 Late 2020 MSD22',
        imgLeft: '/img/catalog/macbook.jpg',
        imgCenter: '/img/catalog/macbook-2.jpg',
        imgRight: '/img/catalog/macbook-3.jpg',
        price: 3732,
        ttlprice: 3732,
        oldPrice: 3800,
        available: 5,
        term: 879801,
        filter: 'macbook',
    },
    {
        id: 3,
        name: 'Ноутбук Apple Macbook Pro 16 Late 2019 (Intel Core i9)',
        imgLeft: '/img/catalog/macbook.jpg',
        imgCenter: '/img/catalog/macbook-2.jpg',
        imgRight: '/img/catalog/macbook-3.jpg',
        price: 7365,
        ttlprice: 7365,
        oldPrice: 7465,
        available: 1,
        term: 879801,
        filter: 'macbook',
    },
    {
        id: 4,
        name: 'Смартфон Apple iPhone 12 Pro 256GB (серый)',
        imgLeft: '/img/catalog/iphone-grey.jpg',
        imgCenter: '/img/catalog/iphone-grey-2.jpg',
        imgRight: '/img/catalog/iphone-grey-3.jpg',
        price: 4140,
        ttlprice: 4199,
        oldPrice: 4299,
        available: 22,
        term: 879802,
        filter: 'iphone',
    },
    {
        id: 5,
        name: 'Смартфон Apple iPhone 12 Pro 256GB (синий)',
        imgLeft: '/img/catalog/iphone.jpg',
        imgCenter: '/img/catalog/iphone-2.jpg',
        imgRight: '/img/catalog/iphone-3.jpg',
        price: 4160,
        ttlprice: 4199,
        oldPrice: 4299,
        available: 12,
        term: 879802,
        filter: 'iphone',
    },
    {
        id: 6,
        name: 'Смартфон Apple iPhone 12 Pro 256GB (золотой)',
        imgLeft: '/img/catalog/iphone-gold.jpg',
        imgCenter: '/img/catalog/iphone-gold-2.jpg',
        imgRight: '/img/catalog/iphone-gold-3.jpg',
        price: 4199,
        ttlprice: 4199,
        oldPrice: 4299,
        available: 14,
        term: 879802,
        filter: 'iphone',
    },
    {
        id: 7,
        name: 'Смартфон Apple iPhone 12 128GB (красный)',
        imgLeft: '/img/catalog/iphone-red.jpg',
        imgCenter: '/img/catalog/iphone-red-2.jpg',
        imgRight: '/img/catalog/iphone-red-3.jpg',
        price: 4100,
        ttlprice: 4199,
        oldPrice: 4299,
        available: 16,
        term: 879802,
        filter: 'iphone',
    },
    {
        id: 8,
        name: 'Смартфон Apple iPhone 12 128GB (черный)',
        imgLeft: '/img/catalog/iphone-black.jpg',
        imgCenter: '/img/catalog/iphone-black-2.jpg',
        imgRight: '/img/catalog/iphone-black-3.jpg',
        price: 4160,
        ttlprice: 4199,
        oldPrice: 4299,
        available: 18,
        term: 879802,
        filter: 'iphone',
    },
    {
        id: 9,
        name: 'Смартфон Apple iPhone 12 128GB (зеленый)',
        imgLeft: '/img/catalog/iphone-green.jpg',
        imgCenter: '/img/catalog/iphone-green-2.jpg',
        imgRight: '/img/catalog/iphone-green-3.jpg',
        price: 4199,
        ttlprice: 4199,
        oldPrice: 4299,
        available: 20,
        term: 879802,
        filter: 'iphone',
    },
    {
        id: 11,
        name: 'Apple iPad 10.2" 2020 32GB LTE MYMH2 (серый космос)',
        imgLeft: '/img/catalog/ipad.jpg',
        imgCenter: '/img/catalog/ipad-2.jpg',
        imgRight: '/img/catalog/ipad-3.jpg',
        price: 1735,
        ttlprice: 1735,
        oldPrice: 1899,
        available: 4,
        term: 879803,
        filter: 'ipad',
    },
    {
        id: 12,
        name: 'Apple iPad Pro 11 (2020) 128GB Wi-Fi MYMH4 (серый космос)',
        imgLeft: '/img/catalog/ipad-pro-gey.jpg',
        imgCenter: '/img/catalog/ipad-pro-gey-2.jpg',
        imgRight: '/img/catalog/ipad-pro-gey-3.jpg',
        price: 2400,
        ttlprice: 2400,
        oldPrice: 2550,
        available: 4,
        term: 879803,
        filter: 'ipad',
    },
    {
        id: 13,
        name: 'Apple iPad Pro 12.9 (2020) 128GB Wi-Fi MYMH7 (серый космос)',
        imgLeft: '/img/catalog/ipad-pro-gey.jpg',
        imgCenter: '/img/catalog/ipad-pro-gey-2.jpg',
        imgRight: '/img/catalog/ipad-pro-gey-3.jpg',
        price: 3130,
        ttlprice: 3130,
        oldPrice: 3200,
        available: 4,
        term: 879803,
        filter: 'ipad',
    },
    {
        id: 14,
        name: 'Беспроводные наушники Apple AirPods Pro',
        imgLeft: '/img/catalog/airpodsPRO.jpg',
        imgCenter: '/img/catalog/airpodsPRO-2.jpg',
        imgRight: '/img/catalog/airpodsPRO-3.jpg',
        price: 520,
        ttlprice: 520,
        oldPrice: 600,
        available: 87,
        term: 879803,
        filter: 'airpods',
    },
    {
        id: 15,
        name: 'Беспроводные наушники Apple AirPods 2 c зарядным футляром MV7N2',
        imgLeft: '/img/catalog/airpods.jpg',
        imgCenter: '/img/catalog/airpods-2.jpg',
        imgRight: '/img/catalog/airpods-3.jpg',
        price: 410,
        ttlprice: 410,
        oldPrice: 440,
        available: 87,
        term: 879803,
        filter: 'airpods',
    },
    {
        id: 16,
        name: 'ТВ-приставка Apple TV 4K 64GB',
        imgLeft: '/img/catalog/tv.jpg',
        imgCenter: '/img/catalog/tv-2.jpg',
        imgRight: '/img/catalog/tv-3.jpg',
        price: 633,
        ttlprice: 633,
        oldPrice: 680,
        available: 22,
        term: 879802,
        filter: 'tv',
    },
    {
        id: 17,
        name: 'Умные часы Apple Watch Series 6 GPS 44мм',
        imgLeft: '/img/catalog/apple-watch.jpg',
        imgCenter: '/img/catalog/apple-watch-2.jpg',
        imgRight: '/img/catalog/apple-watch-3.jpg',
        price: 2528,
        ttlprice: 2528,
        oldPrice: 2598,
        available: 5,
        term: 879802,
        filter: 'apple-watch',
    },
];

export default CATALOG;



